# Generated by Django 4.1 on 2022-11-16 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="团队")),
            ],
        ),
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="姓名")),
                ("job", models.CharField(max_length=16, verbose_name="职位")),
                ("email", models.EmailField(max_length=64, verbose_name="Github邮箱")),
                ("password", models.CharField(max_length=16, verbose_name="账号密码")),
                ("message", models.TextField(verbose_name="信息补充")),
                (
                    "depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app01.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[
                            (1, "紧急"),
                            (2, "重要"),
                            (3, "重要且紧急"),
                            (4, "可以展缓"),
                            (5, "待定义"),
                        ],
                        default=5,
                        verbose_name="状态",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="任务名称")),
                ("detail", models.TextField(verbose_name="任务细节")),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.userinfo",
                        verbose_name="任务人",
                    ),
                ),
            ],
        ),
    ]
