# Generated by Django 4.1 on 2022-11-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_alter_userinfo_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "待开发"),
                    (2, "正在开发"),
                    (3, "开发完成，测试中"),
                    (4, "修改bug中"),
                    (5, "完成"),
                ],
                default=1,
                verbose_name="任务进行状态",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "紧急"), (2, "重要"), (3, "重要且紧急"), (4, "可以展缓"), (5, "待定义")],
                default=5,
                verbose_name="任务等级",
            ),
        ),
    ]
